"""sessions_history

Revision ID: 0d62e2168233
Revises: 7494f4776c67
Create Date: 2024-10-03 04:12:52.488972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d62e2168233'
down_revision: Union[str, None] = '7494f4776c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['training_subscriptions.id'], name=op.f('fk_training_sessions_subscription_id_training_subscriptions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_sessions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_sessions')
    # ### end Alembic commands ###
