"""training_plans

Revision ID: 8044fa55c26e
Revises: 6481bbf01f06
Create Date: 2024-09-30 01:59:55.444358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8044fa55c26e'
down_revision: Union[str, None] = '6481bbf01f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('one_time_personal', 'one_time_split', 'personal_count', 'personal_split', name='trainingtypes'), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.tg_id'], name=op.f('fk_training_plans_trainer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_plans'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_plans')
    # ### end Alembic commands ###
