"""subscribes

Revision ID: f022722bfcff
Revises: 8044fa55c26e
Create Date: 2024-10-01 14:59:50.302859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f022722bfcff'
down_revision: Union[str, None] = '8044fa55c26e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('buy_date', sa.DateTime(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['training_plans.id'], name=op.f('fk_training_subscriptions_plan_id_training_plans')),
    sa.ForeignKeyConstraint(['subscriber_id'], ['users.tg_id'], name=op.f('fk_training_subscriptions_subscriber_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_subscriptions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_subscriptions')
    # ### end Alembic commands ###
